language: cpp # or other C/C++ variants

cache: ccache

dist: trusty
sudo: required

#env:
#  - COMPILER: MXE64
#  - COMPILER: MXE32
#  - COMPILER: CLANG
#  - COMPILER: GCC


matrix:
    include:
      - os: linux  
        env: COMPILER=MXE64 
        

      #- os: linux  
      #  env: COMPILER=MXE32
        

      - os: linux  
        env: COMPILER=GCC

      #- os: linux  
      #  env: COMPILER=CLANG
        
      - os: osx
        osx_image: xcode7.3

      #- os: osx
      #  osx_image: xcode8
        
before_script: 
  - echo -e "Host ns392452.ip-176-31-109.eu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - if [ $TRAVIS_OS_NAME = linux ]  && ([  $COMPILER = GCC ] || [  $COMPILER = CLANG ]) ; then . .travis/setup_linux.sh; fi
  - if [ $TRAVIS_OS_NAME = linux ]  && ([  $COMPILER = MXE32 ] || [  $COMPILER = MXE64 ]) ; then . .travis/setup_mxe.sh; fi
  - if [ $TRAVIS_OS_NAME = osx ]  ; then . .travis/setup_osx.sh; fi

script: 
  - if [ $TRAVIS_OS_NAME = linux ]  && ([  $COMPILER = GCC ] || [  $COMPILER = CLANG ]) ; then . .travis/build_linux.sh; fi
  - if [ $TRAVIS_OS_NAME = linux ]  && ([  $COMPILER = MXE32 ] || [  $COMPILER = MXE64 ]) ; then . .travis/build_mxe.sh; fi
- if [ $TRAVIS_OS_NAME = osx ]  ; then . .travis/build_osx.sh; fi
