dist: trusty
sudo: required

#env:
#  - COMPILER: MXE64
#  - COMPILER: MXE32
#  - COMPILER: CLANG
#  - COMPILER: GCC


matrix:
    include:
      - os: linux  
        env: COMPILER: MXE64     

      - os: linux  
        env: COMPILER: MXE32

      - os: linux  
        env: COMPILER: GCC

      - os: linux  
        env: COMPILER: CLANG
        
      - os: osx
        osx_image: xcode7.2

before_script: . .travis/setup.sh

script: . .travis/build.sh
