dist: trusty
sudo: required
language: cpp
install:
- echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee -a /etc/apt/sources.list
- sudo  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
- sudo apt-get update
-  sudo apt-get install -y mxe-i686-w64-mingw32.shared-qtbase
- PATH=${PATH}:/usr/lib/mxe/usr/bin:/usr/lib/mxe/tools
#- git submodule init && git submodule update

before_script:
- echo ${TRAVIS_BUILD_DIR}
- cd ${TRAVIS_BUILD_DIR}
- mkdir build
- cd build
script:
- i686-w64-mingw32.shared-cmake -DCMAKE_BUILD_TYPE=Release .. -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR} -DOPTION_BUILD_CCVIEWER=OFF
- make install -j 3
- cd ${TRAVIS_BUILD_DIR}
#- wget https://raw.githubusercontent.com/mxe/mxe/master/tools/copydlldeps.sh; chmod a+x copydlldeps.sh
- copydlldeps.sh -c -F ./CloudCompare -d ./CloudCompare -R /usr/lib/mxe
- tar -zcvf cloudcompare-${TRAVIS_COMMIT}.tar.gz CloudCompare
- curl -X PUT -u ${OWNCLOUD_USER}:${OWNCLOUD_PASSWORD} "https://ns392452.ip-176-31-109.eu/owncloud/remote.php/webdav/software/cloudcompare-${TRAVIS_COMMIT}.tar.gz" --data-binary @"cloudcompare-${TRAVIS_COMMIT}.tar.gz" --insecure
