dist: trusty
sudo: required

env:  
  matrix:
    - OS=LINUX COMPILER=GCC 
    - OS=LINUX COMPILER=CLANG 
    - OS=MXEWIN BITS=64
    - OS=MXEWIN BITS=32
    
before_script: . .travis/setup.sh

script: . .travis/build.sh
