
matrix:
    include:
      - os: linux        
        dist: trusty
        sudo: required
        env:
          -COMPILER: GCC
        
      - os: osx
        osx_image: xcode7.2

before_script: . .travis/setup.sh

script: . .travis/build.sh
