dist: trusty
sudo: required
language: cpp
install:
- echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" | sudo tee -a /etc/apt/sources.list
- sudo  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
before_script:
- mkdir build
- cd build
script:
- echo ${TRAVIS_BUILD_DIR}
- cd ${TRAVIS_BUILD_DIR}
- mkdir CloudCompare ; cd CloudCompare; touch file.txt; cd ${TRAVIS_BUILD_DIR}
- tar -zcvf cloudcompare-${TRAVIS_COMMIT}.tar.gz CloudCompare
deploy:
  provider: releases
  api_key:
    secure: fZIc8vJ/bITMtxTJhLDXrPZmv/wzhmIJHf6SIGTwg2gd09G/4KZX3xwvFObo+9Z6VxckjW9F9ZAYmOyH2ZIW9s1HYUkFEPJ7ZcJvHJ1Jb4emuoUGqWkrH8+ig3G/h9Ixkqa0n3EzdOEionynd0B0uy+7dlspENAXKP8I/deWEok=
  file: cloudcompare-${TRAVIS_COMMIT}.tar.gz
  skip_cleanup: true
  on:
    branch: newtravis
    tags: true
    


