dist: trusty
sudo: required

#env:
#  - COMPILER: MXE64
#  - COMPILER: MXE32
#  - COMPILER: CLANG
#  - COMPILER: GCC


matrix:
    include:
      - os: linux  
        COMPILER: MXE64     

      - os: linux  
        COMPILER: MXE32

      - os: linux  
        COMPILER: GCC

      - os: linux  
        COMPILER: CLANG
        
      - os: osx
        osx_image: xcode7.2

before_script: . .travis/setup.sh

script: . .travis/build.sh
